### ISSUE TITLE
Lack of com.mindorks.framework.mvp.di.component.DaggerServiceComponent

### ISSUE THREAD

**Issue by xinghui0000** [MindorksOpenSource/android-mvp-architecture#1]
![image](https://cloud.githubusercontent.com/assets/11531887/22615324/8b0d18b8-eacd-11e6-81c9-899fcc39f917.png)

![image](https://cloud.githubusercontent.com/assets/11531887/22615329/a3661efa-eacd-11e6-922e-92cd300a6fe0.png)

**Comment by amitshekhariitbhu** [comment]
@xinghui0000 This will be auto-generated when you build the app, as dagger2 generates code.

**Comment by xinghui0000** [comment]
@amitshekhariitbhu yeah, I got it, thank you

**Comment by vahidmohammadisan** [comment]
how to fix it , i cant build , missing
