### ISSUE TITLE
DisposableComposite isDisposed after fragment resume

### ISSUE THREAD

**Issue by ziglee** [MindorksOpenSource/android-mvp-architecture#10]
https://github.com/MindorksOpenSource/android-mvp-architecture/blob/master/app/src/main/java/com/mindorks/framework/mvp/ui/about/AboutFragment.java#L84

DisposableComposite is disposed after fragment be resumed and it isn't replaced by a valid one.

**Comment by janishar** [comment]
@ziglee 

Thank for the finding. It has been fixed.

https://github.com/MindorksOpenSource/android-mvp-architecture/commit/490d4eb9b91658367656231be9da3d7fcc40bfef
