### ISSUE TITLE
Manifest merger failed

### ISSUE THREAD

**Issue by jbmlaird** [MindorksOpenSource/android-mvp-architecture#18]
Upon installing the relevant libraries and trying to build for the first time it displays this message:

> Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(25.3.0) from [com.android.support:cardview-v7:25.3.0] AndroidManifest.xml:24:9-31
> 	is also present at [com.android.support:recyclerview-v7:25.3.1] AndroidManifest.xml:24:9-31 value=(25.3.1).
> 	Suggestion: add 'tools:replace="android:value"' to \<meta-data\> element at AndroidManifest.xml:22:5-24:34 to override.
> 

Upon adding to AndroidManifest.xml:
```
<meta-data tools:replace="android:value"/>
```

it displays:

> Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

**Comment by ykAR6Bqy5DeG** [comment]
Updating supportLibraryVersion in the application build.gradle to 25.3.1 works.

**Comment by jbmlaird** [comment]
Thank you
