### ISSUE TITLE
Replacing the MainActivity menu with tabs

### ISSUE THREAD

**Issue by gnud** [MindorksOpenSource/android-mvp-architecture#19]
What would be the best way to have the MvpPresenter inside a tabs adapter ?

**Comment by gnud** [comment]
What I tried so far is adding <FrameLayout> in the main activity's xml layout along side a TabLayout for navigation, whenever I click on tab item it calls needed cases e.g: mPresenter.onDrawerOptionAboutClick();
But, in method showAboutFragment instead of using the cl_root_view I use the id of the FrameLayout.

Is my method a good approach ?

**Comment by janishar** [comment]
@gnud Refer to this link:
https://blog.mindorks.com/essential-guide-for-designing-your-android-app-architecture-mvp-part-3-dialog-viewpager-and-7bdfab86aabb
