### ISSUE TITLE
the class name aboutFragment.java is error?

### ISSUE THREAD

**Issue by insomniatt** [MindorksOpenSource/android-mvp-architecture#2]
![image](https://cloud.githubusercontent.com/assets/853376/22616605/fefd8c5e-eaea-11e6-8578-65054f773dc0.png)

**Comment by amitshekhariitbhu** [comment]
@insomniatt  It has been corrected.

**Comment by insomniatt** [comment]
I'd like your open source project very much. Thanks a lot.
