### ISSUE TITLE
Update UI in Service?

### ISSUE THREAD

**Issue by giaotuancse** [MindorksOpenSource/android-mvp-architecture#27]
Hi guys,
I'm a new guys trying to implement MVP with dependencies injection to new app. 
I have a question about working with Service in MVP structure.
Is there a best way to update UI in a service in this architecture? (Ex : SyncService in this example).
Or I have to update through presenter? If i have to update through presenter, what should I do?

And how about Broadcast Receiver from system. Is there a best practice to do that also ?

Thank you so much!

**Comment by amitshekhariitbhu** [comment]
@giaotuancse I think if you want to update UI from the service, better use LocalBroadcast for this.

**Comment by janishar** [comment]
@giaotuancse If you want to update the UI from service then either use **LocalBroadcast receiver for a started service** 
**OR** 
use the **IBinder interface with Handlers for a binded service**.

Refer to this link:
https://developer.android.com/guide/components/services.html
