### ISSUE TITLE
Why all of data implements is in AppDataManager?

### ISSUE THREAD

**Issue by alongj** [MindorksOpenSource/android-mvp-architecture#28]
It's very strange . Is there some better way do this?

**Comment by amitshekhariitbhu** [comment]
Yes, we are thinking on this simplify it. May be we can insert interactors between these.

**Comment by alongj** [comment]
I do this in kotlin by delegete. 
`class DataManager(api: ApiDataManager, db: DbManager): ApiInterface by api, DbInterface by db`

**Comment by alongj** [comment]
Just Syntactic sugar, not Solution

**Comment by janishar** [comment]
We have made the modifications. Please refer to this repository which simplifies it into interactors:
[android-mvp-interactor-architecture)](https://github.com/MindorksOpenSource/android-mvp-interactor-architecture)
