### ISSUE TITLE
Don't cast the ApplicationContext to your MvpApp

### ISSUE THREAD

**Issue by tmtron** [MindorksOpenSource/android-mvp-architecture#3]
In your [MvpApp class](https://github.com/MindorksOpenSource/android-mvp-architecture/blob/master/app/src/main/java/com/mindorks/framework/mvp/MvpApp.java#L48) you cast the `ApplicationContext` to your `MvpApp`.

`return (MvpApp) context.getApplicationContext();`

This is wrong: see this [SO Answer](http://stackoverflow.com/a/6760019/6287240) for details:
> So if you want the Application class you registered in the Manifest, you should never call getApplicationContext() and cast it to your application, because it may not be the application instance (which you obviously experienced with the test framework).

**Comment by janishar** [comment]
@tmtron 
Can you provide an example where the context.getApplicationContext() will provide a different context than the one which subclasses the Application and provided in the manifest?

You can also refer to this:
https://developer.android.com/reference/android/content/Context.html#getApplicationContext()
`Return the context of the single, global Application object of the current process.`

**Comment by tmtron** [comment]
I've hit that problem sometime ago in one of my test apps. That's when I found the referenced [SO question](http://stackoverflow.com/questions/5018545/getapplication-vs-getapplicationcontext/6760019#6760019).   and learned the hard way that the `Application` is not the same as the `ApplicationContext`.

If you read your reference carefully, you will notice that it does **not** say:

>Return the single, global Application object

but 

> Return **the context of** the single, global Application object

which may be different in some situations: see the [SO question](http://stackoverflow.com/questions/5018545/getapplication-vs-getapplicationcontext/6760019#6760019).  
So it works fine most of the time, but may blow up on some test-tools, emulators, or vendor specific Android versions.

However, apparently it works for you and after all it's your app. Feel free to close the issue.

On the other hand, you only use `MvpApp.get(this)` in 2 places and the fix is as easy as changing the method to:

```
    public static MvpApp get(Application application) {
        return (MvpApp) application;
    }

```
and the calls to

`MvpApp.get(this.getApplication())`

**Comment by janishar** [comment]
@tmtron 

I appreciate the point you have put forward. I want be be clear so that I don't arrive at a conclusion without any proof. 

It's an app for and by the community. I will highly appreciate if we go deep into this issue.

If you dive into the code of Android:

MvpApp extends Application
Application extends ContextWrapper
ContextWrapper extends Context 

So, the context will be able to cast into Application object if it is the context of the Application.
If the the context of the single global application is provided then we will be able to cast in into the Application object.

The point of using the context to access the MvpApp is that any component should be able to access the public methods in the MvpApp not just Activity.

We have a solution for that too by using a reference singleton of the MvpApp but unless we are very clear about the cases where the current implementation will fail, we should try explore the possibilty.

Thanks.

**Comment by tmtron** [comment]
>It's an app for and by the community.

That's why I raised the issue in the first place. I hope that many people will see and use this clean application. It is very useful for learning. 
Thus, it is very important to avoid any possible issues.

>So, the context will be able to cast into Application object if it is the context of the Application.

When the Context instance is our Application instance, the cast will or course work. But that is not guaranteed.  
You can simply check this in the Android source code (Activity.java):
```
    final void attach(Context context, ..., Application application, ..
```
It gets a context and an application object (which is a subclass of Context). So nothing keeps the environment (may it be an Emulator or a vendor specific Android version) from passing 2 different objects.
Apparently our environments  pass the same (Application) object for both parameters, but nothing keeps them from passing in 2 totally independent objects and then your casts will fail.

Unfortunately it seems, I have already deleted my test-app where I hit this problem. But over 200 up-votes on the SO answer should be a good indication that this is something that actually happens (albeit not very often).

>The point of using the context to access the MvpApp is that any component should be able to access the public methods in the MvpApp not just Activity.

Which is an understandable goal, but it simply does not work in all cases. e.g. in a [BroadcastReceiver](https://developer.android.com/reference/android/content/BroadcastReceiver.html) you have no access to the Application object - you only get a context. Again, the current implementations may pass you the Application object, but there's no guarantee.

>We have a solution for that too by using a reference singleton of the MvpApp

That's a viable solution that will always work. BTW: this is also what the [Android docs](https://developer.android.com/reference/android/app/Application.html) recommend:
>Note: There is normally no need to subclass Application. In most situations, static singletons can provide the same functionality in a more modular way. If your singleton needs a global context (for example to register broadcast receivers), include Context.getApplicationContext() as a Context argument when invoking your singleton's getInstance() method.

**Comment by janishar** [comment]
> It gets a context and an application object (which is a subclass of Context). So nothing keeps the environment (may it be an Emulator or a vendor specific Android version) from passing 2 different objects.

So, context.getApplicationContext() will provide Same Application instance or different in certain cases?

You help me recreate this issue.

**Comment by janishar** [comment]
@tmtron 

I have made changes in the repo so no explicit casting it to be done and implemented it now as google has provided in its sample project for this.

Thanks for your input.

**Comment by tmtron** [comment]
thanks for your application :)
