### ISSUE TITLE
Update dagger to 2.10+

### ISSUE THREAD

**Issue by owolp** [MindorksOpenSource/android-mvp-architecture#32]
Do you plan to update dagger to 2.10+ and the newly introduced [dagger.android](https://github.com/google/dagger/tree/dagger-2.10/java/dagger/android) framework?

**Comment by anandwana001** [comment]
We will be updating soon this repository with latest dagger release. For a reference, you can checkout [this](https://github.com/MindorksOpenSource/android-mvvm-architecture) project where we had used the latest dagger.
