### ISSUE TITLE
CompositeDisposable dispose when detaching fragment

### ISSUE THREAD

**Issue by madnotdead** [MindorksOpenSource/android-mvp-architecture#42]
I'm attaching and detaching fragments, when i first add the fragment and call the presenter methods eveything works ok but after deataching and attaching again the compositeDisposable is disposed and doesn't execute anything. Any clue?

```
 switch (screenKey) {
                case Screens.STATUS_SCREEN:
                    fm.beginTransaction()
                            .detach(historyFragment)
                            .detach(profileFragment)
                            .attach(statusFragment)
                            .commitNow();
                    break;
                case Screens.HISTORY_SCREEN:
                    fm.beginTransaction()
                            .detach(profileFragment)
                            .detach(statusFragment)
                            .attach(historyFragment)
                            .commitNow();
                    break;
                case Screens.PROFILE_SCREEN:
                    fm.beginTransaction()
                            .detach(historyFragment)
                            .detach(statusFragment)
                            .attach(profileFragment)
                            .commitNow();
                    break;
            }
```

EDIT: I have a MainActivity which has an fragment_container that i change over bottonNavigationBar selection.

**Comment by amitshekhariitbhu** [comment]
I think we need to change the `dispose()` to `clear()`.

**Comment by amitshekhariitbhu** [comment]
[Refer this link](https://stackoverflow.com/questions/39203791/how-to-use-compositedisposable-of-rxjava-2).

**Comment by madnotdead** [comment]
Changing from dispose() to clear() resolve this issue. I think that it's ok in this way because the dispose is tie to BasePresenter lifecycle and this should avoid leaked CompositeDisposable if I'm correct.
