### ISSUE TITLE
Retrofit with Progress Bars

### ISSUE THREAD

**Issue by Shaw4774** [MindorksOpenSource/android-mvp-architecture#43]
This a very good example of MVP Architecture Pattern. Please add retrofit library implementation in this project. So that one can easily understand how to show a progress bar when data is loading and when to hide it.

**Comment by amitshekhariitbhu** [comment]
Ok we can add this also.

**Comment by Shaw4774** [comment]
Thanks a lot.

**Comment by janishar** [comment]
@Shaw4774 Refer to this branch for Retrofit implementation:

https://github.com/MindorksOpenSource/android-mvp-architecture/tree/rxjava-retrofit-greendao-based-mvp
