### ISSUE TITLE
Cannot resolve DaggerActivityComponent in com.mindorks.framework.mvp.ui.base.BaseActivity.java

### ISSUE THREAD

**Issue by midoreigh** [MindorksOpenSource/android-mvp-architecture#5]
`com.mindorks.framework.mvp.di.component.DaggerActivityComponent` is missing

I am new to android. Never used Dagger before. So please help.

**Comment by janishar** [comment]
@midoreigh 

Just build your project once:
`DaggerActivityComponent` will be generated by Dagger during build time.

Read these two Articles by me to understand how Dagger works:
1. https://blog.mindorks.com/introduction-to-dagger-2-using-dependency-injection-in-android-part-1-223289c2a01b#.j5elbi84n
2. https://blog.mindorks.com/introduction-to-dagger-2-using-dependency-injection-in-android-part-2-b55857911bcd#.nen079d5b

**Comment by midoreigh** [comment]
Thank you. That solved the issue.

**Comment by BismeetSingh** [comment]
Not working at all.

**Comment by midoreigh** [comment]
@BismeetSingh It should work after rebuilding the project. Hit clean and after finishing cleaning you will be able to run it

**Comment by mariaanko** [comment]
we had the same problem: just go to terminal and rebuild the project with: ./gradlew clean assemble

**Comment by GajanandSwamy** [comment]
implementation "com.google.dagger:dagger-android-support:2.11"
implementation "com.google.dagger:dagger:2.11"
annotationProcessor "com.google.dagger:dagger-compiler:2.11"

for me its changing the dependencies in build.graddle...worked
