### ISSUE TITLE
Use getSchedulerProvider and  getCompositeDisposable in services.

### ISSUE THREAD

**Issue by Themesaul** [MindorksOpenSource/android-mvp-architecture#66]
What is the way to use getCompositeDisposable and getSchedulerProvider in a service (For example SyncService)?

I have several services, one of them from Firebase (to update the user's push token) but I have to make an HTTP call from the service and I could not do it.  I tried using dependency injection but I could not.

**Comment by amitshekhariitbhu** [comment]
Create a `baseService` and inject in that. Have the method `getCompositeDisposable` and `getSchedulerProvider` in that `baseService`.

**Comment by Themesaul** [comment]
It works perfect. It is very clean. It is perfect

**Comment by dpnkrg** [comment]
example?
