### ISSUE TITLE
AppDataManager is Anti Pattern?!

### ISSUE THREAD

**Issue by Drjacky** [MindorksOpenSource/android-mvp-architecture#72]
I've built my sample project as same as this Architecture.  
Then someone reviewed my work and told me that `AppDataManager` is an Anti-pattern.

I do not really agree with him, but would you please explain or guess why?

**Comment by IslamSalah** [comment]
Check this [article](https://blog.mindorks.com/android-mvp-architecture-extension-with-interactors-and-repositories-bd4b51972339) for decentralization of `DataManager` .
