### ISSUE TITLE
Can't use Generic Class on getObjectSingle

### ISSUE THREAD

**Issue by indraAsLesmana** [MindorksOpenSource/android-mvp-architecture#74]
https://github.com/MindorksOpenSource/android-mvp-architecture/blob/ef9de86274b76e3a7ca7523ca7c258203cb8197d/app/src/main/java/com/mindorks/framework/mvp/data/network/AppApiHelper.java#L66

https://i.stack.imgur.com/S8p75.png
https://i.stack.imgur.com/Gyico.png

**Comment by amitshekhariitbhu** [comment]
I think the current version of library does not support this.

**Comment by amitshekhariitbhu** [comment]
I will check if it is possible or not.

**Comment by indraAsLesmana** [comment]
thanks, waiting if it possible.
I very want that response put in the same object wrapper
`class Wrapper<T> {
    @Expose
    @SerializedName("message")
    var message: String = ""
    @Expose
    @SerializedName("meta")
    lateinit var meta: Meta
    @Expose
    @SerializedName("result")
    var data: T? = null

    class Meta {
        @Expose
        @SerializedName("total")
        var total: Int = 0
        @Expose
        @SerializedName("offset")
        var offset: Int = 0
        @Expose
        @SerializedName("limit")
        var limit: Int = 0
    }
}`

**Comment by indraAsLesmana** [comment]
(solved) Wrapper<SignInResponse>().javaClass 

thanks.
